name: Python CI

on:
  push:
    branches: 
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # or whatever version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover -s tests -p "test_*.py"
        coverage report
        coverage html  # optional, for HTML report

    - name: Fail if coverage is below threshold (80%)
      run: |
        coverage report --fail-under=80
